src/web_app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from pkg.utils import commit
from pkg.med_core import Patient, Characteristic, Drug, Treatment, MedicationRegimen, AlternativeTreatments, FollowUp
from pkg.ZODB_manager import RegistryManager
from pkg.graph_vis import GraphVisualizer

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')



def get_patient_characteristics():
    """Helper function to fetch populations, primary indications, and other characteristics."""
    with RegistryManager() as rm:
        patient_registry = rm.get_registry('patient_registry')
        
        all_pops = set()
        all_pis = set()
        all_chars_name = set()
        all_chars_type = set()

        for patient in patient_registry.values():
            for char, _, _ in patient.chars:
                if char.type == 'Population':
                    all_pops.add(char.name)
                elif char.type == 'Primary Indication':
                    all_pis.add(char.name)
                else:
                    all_chars_name.add(char.name)
                    all_chars_type.add(char.type)

        return list(all_pops), list(all_pis), list(all_chars_name), list(all_chars_type)
                                                   

@main.route('/api/characteristics', methods=['GET'])
def fetch_charracteristics():
    try:
        all_pops, all_pis, all_chars_name, all_chars_type = get_patient_characteristics()
        return jsonify({
            'population': list(all_pops),
            'primary_indication': list(all_pis),
            'other_characteristics_name': list(all_chars_name),
            'other_characteristics_type': list(all_chars_type)
        })
    
    except Exception as e:
        return jsonify({'error': f'Failed to fetch characteristics: {str(e)}'}), 500

        

@main.route('/patients', methods=['GET', 'POST'])
def patients():
    all_pops, all_pis, all_chars_name, all_chars_type = [], [], [], []
    try:
        all_pops, all_pis, all_chars_name, all_chars_type = get_patient_characteristics()                 
        if request.method == 'POST':
            try:
                population = request.form['population']
                primary_indication = request.form['primary_indication']
                char_type = request.form['char_type']
                char_name = request.form['char_name']

                matching_patients = []
                with RegistryManager() as rm:
                    patient_registry = rm.get_registry('patient_registry')
                    for patient in patient_registry.values():
                        matches_pop = any(char.name == population for char, *_ in patient.chars) if population else True
                        matches_pi = any(char.name == primary_indication for char, *_ in patient.chars) if primary_indication else True
                        matches_char_type = any(char.type == char_type for char, *_ in patient.chars) if char_type else True
                        matches_char_name = any(char.name == char_name for char, *_ in patient.chars) if char_name else True

                        if (
                            matches_pop and
                            matches_pi and
                            matches_char_type and
                            matches_char_name
                        ):
                            matching_patients.append(patient)
                    
                    print("patient_registry size:", len(patient_registry))

                    # Visualize the graph
                    if matching_patients:
                        graph_vis = GraphVisualizer()
                        for patient in matching_patients:
                            graph_vis.add_patient(patient)
                        graph_vis.visualize_interactive()
                        flash(f'Found {len(matching_patients)} matching patients.', 'success')
                    else:
                        flash(f'No patiens found matching the filter criteria.', 'danger')
                    # size = float(request.form['size'])

                    # population_char = Characteristic('Population', population)
                    # patient = Patient(size, population_char)
                    # pi_char = Characteristic('Primary Indication', primary_indication)
                    # patient.add_characteristic(pi_char)

                    # commit(patient)
                    # flash('Patient added successfully!', 'success')
            
            except Exception as e:
                flash(f'Error adding patient: {e}', 'danger')
        return render_template(
            'patients.html',
            all_pops = all_pops,
            all_pis = all_pis,
            all_chars_name = all_chars_name,
            all_chars_type = all_chars_type
            )
    
    except Exception as e:
        flash(f'Error fetching patient data: {e}', 'danger')
        return render_template(
            'patients.html',
            all_pops = all_pops,
            all_pis = all_pis,
            all_chars_name = all_chars_name,
            all_chars_type = all_chars_type
            )
    

@main.route('/filter_patient/<patient_id>', methods=['GET'])
def filter_patient(patient_id):
    graph_vis = GraphVisualizer()
    graph_vis.load_data()
    graph_vis.filter_graph_by_patient(patient_id)

    return jsonify({"message": f"Graph updated for patient {patient_id}"})


@main.route('/drugs', methods=['GET', 'POST'])
def drugs():
    if request.method == 'POST':
        try:
            name = request.form['name']
            strength = request.form['strength']

            drug = Drug(name, strength)
            commit(drug)
            flash('Drug added successfully!', 'success')
        except Exception as e:
            flash(f'Error adding drug: {e}', 'danger')
    return render_template('drugs.html')


@main.route('/treatments', methods=['GET'])
def treatments():
    try:
        with RegistryManager() as rm:
            drug_registry = rm.get_registry('drug_registry')
            drugs = [drug.to_dict() for drug in drug_registry.values()]
            
            treatment_registry = rm.get_registry('treatment_registry')
            medical_treatments = [treatment.to_dict() for treatment in treatment_registry.values()]

        return render_template('treatments.html', drugs=drugs, medical_treatments=medical_treatments)
    
    except Exception as e:
        flash(f"Error fetching registries: {e}", 'danger')
        return render_template('treatments.html', drugs=[], medical_treatments=[])



@main.route('/treatments/general', methods=['POST'])
def add_general_treatment():
    try:
        name = request.form['treatment_name']
        treatment = Treatment.get_or_create(name)
        commit(treatment)
        flash(f'General Treatment added successfully!', 'success')
    except Exception as e:
        flash(f'Error adding treatment: {e}' , 'danger')
    
    return redirect(url_for('main.treatments'))


@main.route('/treatments/regimen', methods=['POST'])
def add_medical_regimen():
    try:
        name = request.form['medical_regimen_name']
        drugs = request.form.getlist('medical_regimen_drugs')
        medication = MedicationRegimen.get_or_create(name)

        for drug_id in drugs:
            drug_name, drug_str = drug_id.split('|')
            drug = Drug(drug_name, drug_str)
            annual_patient_con = int(request.form[f'annual_con_{drug_name}'])
            medication.add_drug(drug, annual_patient_con)

        commit(medication)
        flash(f'Medication Regimen add successfully!', 'success')
    except Exception as e:
        flash(f'Error adding Medication Regimen: {e}', 'danger')
    return redirect(url_for('main.treatments'))


@main.route('/treatments/alternative', methods=['POST'])
def add_alt_treatment():
    try:
        name = request.form['alt_name']
        selelcted_treatments = request.form.getlist('alternative_treatments')
        rates = [
            float(request.form.get(f'rate_{treatment_name}', 1.0))
            for treatment_name in selelcted_treatments
        ]

        treatments = [Treatment.get_or_create(t_name) for t_name in selelcted_treatments]
        alternative_treatment = AlternativeTreatments.get_or_create(*treatments, rates=rates)
        
        commit(alternative_treatment)
        flash('Alternative Treatment added successfully!', 'success')
    except Exception as e:
        flash(f'Error adding alternative treatment: {e}', 'danger')
    return redirect(url_for('main.treatments'))


@main.route('/followups', methods=['GET', 'POST'])
def followups():
    if request.method == 'POST':
        try:
            patient_id = request.form['patient_id']
            os_rate = float(request.form['os_rate'])

            # Retrieve Patient and Create Follow-Up
            # Assuming patient retrieval logic is defined
            patient = Patient.get(patient_id)
            followup = FollowUp(patient, os_rate)
            followup.add_to_patient()
            commit(followup)
            flash('Follow-Up added successfully!', 'success')
        except Exception as e:
            flash(f'Error adding follow-up: {e}', 'danger')

    return render_template('followups.html')


@main.route('/chars', methods=['GET', 'POST'])
def chars():
    if request.method == 'POST':
        try:
            type = request.form['type']
            name = request.form['name']

            char = Characteristic(type, name)
            commit(char)
            flash('Characteristic added successfully!', 'success')
        except Exception as e:
            flash(f'Error adding Characteristic: {e}', 'danger')
    return render_template('chars.html')


@main.route('/interactive_graph')
def interactive_graph():
    vis = GraphVisualizer()
    vis.load_data()
    vis.visualize_interactive()

    return """
    <h3>Graph</h3>

src/web_app/templates/chars.html
{% extends "index.html" %} {% block content %}
<h1>Characteristics</h1>

<form action="{{ url_for('main.chars') }}" method="POST">
  <label for="name">Type:</label>
  <input type="text" id="type" name="type" required />

  <label for="name">Name:</label>
  <input
    type="text"
    id="name"
    name="name"
    required
  />

  <button type="submit">Add Characteristics</button>
</form>
{% endblock %}

src/web_app/templates/drugs.html
{% extends "index.html" %} {% block content %}
<h1>Drugs</h1>

<form action="{{ url_for('main.drugs') }}" method="POST">
  <label for="name">Drug Name:</label>
  <input type="text" id="name" name="name" required />

  <label for="strength">Strength:</label>
  <input
    type="text"
    id="strength"
    name="strength"
    placeholder="e.g., 450 mg"
    required
  />

  <button type="submit">Add Drug</button>
</form>
{% endblock %}

src/web_app/templates/followups.html
{% extends "index.html" %} {% block content %}
<h1>Follow-Up Management</h1>

<form action="{{ url_for('main.followups') }}" method="POST">
  <label for="patient">Select Patient:</label>
  <select id="patient" name="patient" required>
    {% for patient in patients %}
    <option value="{{ patient['id'] }}">{{ patient['id'] }}</option>
    {% endfor %}
  </select>

  <label for="overall_survival">Overall Survival:</label>
  <input
    type="number"
    id="overall_survival"
    name="overall_survival"
    step="0.01"
    min="0"
    max="1"
    required
  />

  <button type="submit">Add Follow-Up</button>
</form>
{% endblock %}

src/web_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Minos</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Include jQuery first -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Include Select2 -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
      rel="stylesheet"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <!-- Include vis.js Library -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vis-network@9.0.0/umd/vis-network.min.js"></script>

    <!-- Now include your own JS script -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  </head>
  <body>
    <div class="container">
      <div class="image-section">
        <h1 class="navigation-title">Minos</h1>
        <p class="navigation-title-desc">Patient Map Management System</p>
        <img
          src="{{ url_for('static', filename='images/maze-background.png') }}"
          alt="Background Image"
        />
      </div>
      <div class="navigation-section">
        <ul>
          <li><a href="{{ url_for('main.index') }}">Home</a></li>
          <li><a href="{{url_for('main.chars')}}">Characteristics</a></li>
          <li><a href="{{ url_for('main.drugs') }}">Drugs</a></li>
          <li><a href="{{ url_for('main.treatments') }}">Treatments</a></li>
          <li><a href="{{ url_for('main.patients') }}">Patients</a></li>
        </ul>
      </div>
      <div class="form-section">{% block content %}{% endblock %}</div>
    </div>
  </body>
</html>

src/web_app/templates/patients.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Patients</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles_patient.css') }}"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Include jQuery first -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Include Select2 -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
      rel="stylesheet"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <!-- Include vis.js Library -->
    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/vis-network@9.0.0/umd/vis-network.min.js"
    ></script>

    <!-- Now include your own JS script -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  </head>
  <body>
    <div class="container">
      
      <!-- Navigation Section at the Top -->
      <div class="navigation-section">
        <!-- Hamburger Icon + Menu first -->
        <div class="nav-container">
          <div class="nav-icon">
            <img src="{{ url_for('static', filename='images/hamburger-menu.png') }}" alt="Menu" />
          </div>
          <div class="nav-menu">
            <ul>
              <li><a href="{{ url_for('main.index') }}">Home</a></li>
              <li><a href="{{url_for('main.chars')}}">Characteristics</a></li>
              <li><a href="{{ url_for('main.drugs') }}">Drugs</a></li>
              <li><a href="{{ url_for('main.treatments') }}">Treatments</a></li>
            </ul>
          </div>
        </div>

        <!-- Title + Description second -->
        <div class="nav-info">
          <h2 class="navigation-title">Minos</h2>
          <p class="navigation-title-desc">Patient Map Management System</p>
        </div>
      </div>

      <!-- Patient Form Section -->
      <div class="search-section">
        <h3>Search</h3>
        <form
          action="{{ url_for('main.patients') }}"
          method="POST"
          class="flex-search"
        >
          <div class="search-group">
            <label for="population">Population:</label>
            <select name="population" id="population" class="select2">
              <option value="" disabled selected hidden></option>
              {% for pop in all_pops %}
              <option value="{{ pop }}">{{ pop }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="search-group">
            <label for="primary_indication">Primary Indication:</label>
            <select
              name="primary_indication"
              id="primary_indication"
              class="'select2"
            >
              <option value="" disabled selected hidden></option>
              {% for pi in all_pis %}
              <option value="{{ pi }}">{{ pi }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="search-group">
            <label for="char_type">Characteristics type:</label>
            <select name="char_type" id="char_type" class="'select2">
              <option value="" disabled selected hidden></option>
              {% for ctype in all_chars_type %}
              <option value="{{ ctype }}">{{ ctype }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="search-group">
            <label for="char_name">Characteristics name:</label>
            <select name="char_name" id="char_name" class="'select2">
              <option value="" disabled selected hidden></option>
              {% for cname in all_chars_name %}
              <option value="{{ cname }}">{{ cname }}</option>
              {% endfor %}
            </select>
          </div>
          <button type="submit">Search</button>
          <!-- <label for="size">Size:</label>
          <input type="number" name="size" id="size" required />
          
          <button type="submit">Add Patient</button> -->
        </form>
      </div>
      <div class="graph-section">
        <h3>Patient Map</h3>
        <iframe
          src="{{ url_for('static', filename='pyvis_graph.html') }}"
          width="100%"
          height="800"
        ></iframe>
      </div>
    </div>
  </body>
</html>

src/web_app/templates/treatments.html
{% extends "index.html" %} {% block content %}
<h1>Treatments</h1>

<!-- General Treatment Form -->
<section>
  <h2>General Treatment</h2>
  <form action="{{ url_for('main.add_general_treatment') }}" method="POST">
    <label for="treatment_name">Name:</label>
    <input type="text" id="treatment_name" name="treatment_name" required />
    <button type="submit">Add Treatment</button>
  </form>
</section>

<hr />

<!-- Medical Regimen Form -->
<section>
  <h2>Medical Regimen</h2>
  <form action="{{ url_for('main.add_medical_regimen') }}" method="POST">
    <label for="medical_regimen_name">Name:</label>
    <input
      type="text"
      id="medical_regimen_name"
      name="medical_regimen_name"
      required
    />

    <label for="medical_regimen_drugs">Drugs:</label>
    <select
      id="medical_regimen_drugs"
      name="medical_regimen_drugs"
      multiple
      required
      class="select2"
    >
      {% for drug in drugs %}
      <option value="{{ drug['name'] }}|{{ drug['strength'] }}">
        {{ drug['name'] }} ({{ drug['strength'] }})
      </option>
      {% endfor %}
    </select>

    <!-- Dynamic input fields for drug annual consumption -->
    <div id="drug_inputs"></div>

    <button type="submit">Add Regimen</button>
  </form>
</section>

<hr />

<!-- Alternative Treatment Form -->
<section>
  <h2>Alternative Treatment</h2>
  <form action="{{ url_for('main.add_alt_treatment') }}" method="POST">
    <label for="alternative_name">Name:</label>
    <input type="text" id="alternative_name" name="alternative_name" required />

    <label for="alternative_treatments">Treatments:</label>
    <select
      id="alternative_treatments"
      name="alternative_treatments"
      multiple
      required
      class="select2"
    >
      {% for treatment in medical_treatments %}
      <option value="{{ treatment.name }}">{{ treatment.name }}</option>
      {% endfor %}
    </select>

    <!-- Dynamic rate input fields -->
    <div id="rate_inputs"></div>

    <button type="submit">Add Alternative</button>
  </form>
</section>

{% endblock %}